version: '3'
services:
  api:
    container_name: test-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=${URL_DATABASE}
    depends_on:
      - database
  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
